#!/usr/bin/env bash
# MainSail installation script
# Installs UI and nginx
# Written by Raymond Himle
# Thanks to meteyou
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi

echo "UIl"

apt update
apt install nginx -y
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/mainsail /etc/nginx/sites-enabled/
cd /home/pi/
# Run installation steps defined above

# Unpack root at the end, so files are modified before
unpack /filesystem/root /